.gitignore
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/Flavor.java
back/src/main/java/com/cocktailpick/back/common/BaseEntity.java
back/src/main/java/com/cocktailpick/back/recipe/domain/Recipe.java
back/src/main/java/com/cocktailpick/back/recipe/domain/RecipeItem.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTag.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tags.java
back/src/main/resources/application.properties

Feat/6 칵테일 관련 도메인을 구현한다.

---

back/build.gradle
back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailResponse.java
back/src/main/java/com/cocktailpick/back/cocktail/repository/CocktailRepository.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/recipe/domain/Recipe.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tags.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/recipe/domain/RecipeTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagsTest.java

Feat/10 칵테일 다수 조회 기능을 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/CocktailRepository.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailRequest.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/recipe/domain/Recipe.java
back/src/main/java/com/cocktailpick/back/recipe/domain/RecipeItem.java
back/src/main/java/com/cocktailpick/back/recipe/domain/RecipeItemRepository.java
back/src/main/java/com/cocktailpick/back/recipe/dto/RecipeItemResponse.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTag.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/main/java/com/cocktailpick/back/tag/domain/TagRepository.java
back/src/main/resources/application.properties
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/recipe/domain/RecipeTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagsTest.java

Feat/15 칵테일 추가 기능을 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailDetailResponse.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailResponse.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTag.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java

Feat/13 칵테일 수정 기능을 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/common/BaseEntity.java
back/src/main/java/com/cocktailpick/back/common/configuration/JpaAuditingConfig.java
back/src/main/java/com/cocktailpick/back/recipe/domain/Recipe.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailRepositoryTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/recipe/domain/RecipeTest.java
back/src/test/java/com/cocktailpick/back/tag/controller/TagControllerTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagsTest.java
back/src/test/java/com/cocktailpick/back/tag/service/TagServiceTest.java

Feat/14 칵테일 삭제 기능을 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailCsvReader.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/common/BaseEntity.java
back/src/main/java/com/cocktailpick/back/common/EntityMapper.java
back/src/main/java/com/cocktailpick/back/common/csv/CsvReader.java
back/src/main/java/com/cocktailpick/back/common/csv/OpenCsvReader.java
back/src/main/java/com/cocktailpick/back/tag/controller/TagController.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTag.java
back/src/main/java/com/cocktailpick/back/tag/service/TagCsvReader.java
back/src/main/java/com/cocktailpick/back/tag/service/TagService.java
back/src/main/resources/application.properties
back/src/test/java/com/cocktailpick/back/cocktail/Fixtures.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailRepositoryTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailCsvReaderTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/common/EntityMapperTest.java
back/src/test/java/com/cocktailpick/back/tag/Fixtures.java
back/src/test/java/com/cocktailpick/back/tag/controller/TagControllerTest.java
back/src/test/java/com/cocktailpick/back/tag/service/TagCsvReaderTest.java
back/src/test/java/com/cocktailpick/back/tag/service/TagServiceTest.java

Feat/12 칵테일 DB를 구축한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/TagFilter.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/UserRecommendRequest.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/UserRecommendRequests.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTag.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java

Feat/28 칵테일 추천 API를 구현한다.

---

front/src/api/index.js
front/src/component/admin/EditFormContainer.js
front/src/component/admin/FileUplodeContainer.js
front/src/css/admin/admin.css

Feat/42 관리자 페이지에서 칵테일과 태그를 csv 파일로 추가하는 기능을 구현한다.

---

back/build.gradle
back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailRequest.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/common/EntityMapper.java
back/src/main/java/com/cocktailpick/back/common/advice/GlobalExceptionHandler.java
back/src/main/java/com/cocktailpick/back/common/csv/OpenCsvReader.java
back/src/main/java/com/cocktailpick/back/common/dto/ErrorResponse.java
back/src/main/java/com/cocktailpick/back/common/exceptions/BusinessException.java
back/src/main/java/com/cocktailpick/back/common/exceptions/EntityNotFoundException.java
back/src/main/java/com/cocktailpick/back/common/exceptions/ErrorCode.java
back/src/main/java/com/cocktailpick/back/common/exceptions/InvalidValueException.java
back/src/main/java/com/cocktailpick/back/recipe/domain/Recipe.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/test/java/com/cocktailpick/back/recipe/domain/RecipeTest.java

Feat/41 기본적인 예외처리 기능을 구현한다.

---

back/build.gradle
back/lombok.config

feat: jacoco 적용

---

back/build.gradle
back/src/main/java/com/cocktailpick/back/cocktail/domain/CocktailSearcher.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/common/exceptions/BusinessException.java
back/src/main/java/com/cocktailpick/back/common/util/NumberOfDaily.java
back/src/main/java/com/cocktailpick/back/recipe/domain/RecipeItem.java
back/src/main/java/com/cocktailpick/back/tag/service/TagCsvReader.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailFindStrategyFactoryTest.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailRepositoryTest.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailSearcherTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/common/EntityMapperTest.java
back/src/test/java/com/cocktailpick/back/common/advice/GlobalExceptionHandlerTest.java
back/src/test/java/com/cocktailpick/back/common/domain/DailyDateTest.java
back/src/test/java/com/cocktailpick/back/common/util/NumberOfDailyTest.java
back/src/test/java/com/cocktailpick/back/recipe/domain/RecipeItemTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagsTest.java

Feat/46 누락된 도메인, 서비스 테스트를 구현한다.

---

front/conf/conf.d/default.config
front/package.json
front/src/api/index.js
front/yarn.lock

Feat 50: 배포 환경을 구축한다.

---

back/.gitignore
back/src/main/java/com/cocktailpick/back/common/advice/GlobalExceptionHandler.java
back/src/main/resources/application.properties
back/src/main/resources/logback-spring.xml

Feat/49 로깅 기능을 구현한다.

---

front/src/component/cocktailSearch/CocktailDetailSearch.js
front/src/component/cocktailSearch/RecipeItems.js
front/src/component/cocktailSearch/SearchedCocktail.js
front/src/component/common/CircularBox.js
front/src/component/info/DetailInfo.js
front/src/css/common/circularBox.css
front/src/css/info/detailInfo.css
front/src/router/Routes.js

Feat/34 칵테일 상세 조회 페이지 프론트를 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/CocktailRepository.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailRepositoryTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
front/src/api/index.js
front/src/component/cocktailSearch/CocktailSearch.js

issue: #70
[관련 슬랙 링크](https://6rinkers.slack.com/archives/C0170698NT1/p1596261142003400)
리뷰어 :

Feat/70 칵테일 목록 보여주기 무한 스크롤을 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/CocktailRepository.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailResponse.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
front/src/api/index.js
front/src/component/cocktailSearch/AutoCocktailWord.js
front/src/component/cocktailSearch/AutoCocktailWords.js
front/src/component/cocktailSearch/ScrollFocus.js
front/src/component/cocktailSearch/SearchContainer.js
front/src/component/cocktailSearch/SearchedCocktail.js
front/src/component/recommend/ResultSlide.js
front/src/constants/keyCode.js
front/src/css/cocktailSearch/cocktailSearch.css
front/src/index.css
front/src/router/Routes.js

Feat/53 칵테일 이름 자동완성 기능을 구현한다.

---

README.md
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailCsvReader.java
back/src/test/java/com/cocktailpick/back/cocktail/Fixtures.java
front/src/component/cocktailSearch/CocktailDetailSearch.js
front/src/component/cocktailSearch/SearchContainer.js
front/src/component/cocktailSearch/SearchedCocktail.js
front/src/component/common/Footer.js
front/src/component/common/ServicesSlider.js
front/src/component/home/TodayCocktail.js
front/src/component/recommend/Result.js
front/src/component/recommend/ResultSlide.js
front/src/css/cocktailSearch/cocktailDetailSearch.css
front/src/css/cocktailSearch/cocktailSearch.css
front/src/css/common/circularBox.css
front/src/css/common/footer.css
front/src/css/common/header.css
front/src/css/recommend/question.css
front/src/css/recommend/result.css

Feat/51 칵테일 추천 질답 프론트를 구현한다. - 리팩토링

---

back/src/main/java/com/cocktailpick/back/common/csv/OpenCsvReader.java
front/src/api/index.js

Feat: 75 개발 서버를 배포한다.

---

.gitmodules

Feat/83 서브모듈을 적용한다.

---

back/build.gradle
back/src/main/resources/logback-spring.xml
front/src/api/index.js

Hotfix/95 application properties 설정 버그를 고친다.

---

back/src/main/java/com/cocktailpick/back/cocktail/domain/UserAnswer.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/UserPreferenceAnswer.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/AbvAnswer.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/FlavorAnswer.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/RecommendRequest.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/TagPreferenceAnswer.java

Feat/85 칵테일 추천 DTO를 구현한다.

---

back/build.gradle
back/src/docs/asciidocs/api-docs.adoc
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailDetailResponse.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailResponse.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/docs/CocktailDocumentation.java
back/src/test/java/com/cocktailpick/back/common/documentation/Documentation.java
back/src/test/java/com/cocktailpick/back/tag/controller/TagControllerTest.java
back/src/test/java/com/cocktailpick/back/tag/docs/TagDocumentation.java
front/package-lock.json

Feat/82 API 문서화를 한다.

---

back/src/docs/asciidocs/api-docs.adoc
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/common/controller/PingController.java
back/src/main/java/com/cocktailpick/back/common/domain/BaseEntity.java
back/src/main/java/com/cocktailpick/back/recipe/domain/RecipeItem.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTag.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/test/java/com/cocktailpick/back/common/controller/PingControllerTest.java
back/src/test/java/com/cocktailpick/back/common/docs/PingDocumentation.java

Feat/105 /api/ping 컨트롤러를 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/domain/TagFilter.java
back/src/main/java/com/cocktailpick/back/common/exceptions/ErrorCode.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/main/java/com/cocktailpick/back/tag/domain/TagType.java
back/src/main/java/com/cocktailpick/back/tag/dto/TagRequest.java
back/src/main/java/com/cocktailpick/back/tag/dto/TagResponse.java
back/src/main/java/com/cocktailpick/back/tag/service/TagCsvReader.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/docs/CocktailDocumentation.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailRepositoryTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/tag/Fixtures.java
back/src/test/java/com/cocktailpick/back/tag/controller/TagControllerTest.java
back/src/test/java/com/cocktailpick/back/tag/docs/TagDocumentation.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagsTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/TagTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/TagTypeTest.java
back/src/test/java/com/cocktailpick/back/tag/service/TagCsvReaderTest.java
back/src/test/java/com/cocktailpick/back/tag/service/TagServiceTest.java
front/src/component/admin/cocktail/CocktailEditFormContainer.js
front/src/component/admin/tag/TagAdmin.js
front/src/component/admin/tag/TagHeader.js
front/src/component/admin/tag/TagInput.js
front/src/component/admin/tag/TagItem.js
front/src/component/admin/tag/TagList.js
front/src/utils/admin/tagConverter.js

Feat/100 관리자 페이지에서 태그 타입을 추가하는 기능을 구현한다.

---

back/src/docs/asciidocs/api-docs.adoc
back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/recipe/domain/Recipe.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/main/java/com/cocktailpick/back/tag/domain/TagType.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/docs/CocktailDocumentation.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/tag/Fixtures.java
back/src/test/java/com/cocktailpick/back/tag/domain/TagTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/TagTypeTest.java
back/src/test/java/com/cocktailpick/back/tag/service/TagServiceTest.java
front/package-lock.json
front/src/api/index.js
front/src/component/admin/cocktail/CocktailAdmin.js
front/src/component/admin/cocktail/CocktailEditFormContainer.js
front/src/component/admin/cocktail/CocktailItem.js
front/src/component/admin/cocktail/CocktailListContainer.js
front/src/component/admin/common/FileUplodeContainer.js
front/src/component/admin/tag/TagInput.js
front/src/css/admin/admin.css
front/src/css/admin/cocktailListContainer.css
front/src/css/admin/editFormContainer.css
front/src/utils/admin/cocktailConverter.js
front/src/utils/admin/constant.js

Feat/79 관리자 페이지에 칵테일 수정, 삭제 기능을 구현한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/common/domain/BaseTimeEntity.java
back/src/main/java/com/cocktailpick/back/recipe/domain/RecipeItem.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTag.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/main/java/com/cocktailpick/back/tag/dto/TagRequest.java
back/src/main/java/com/cocktailpick/back/tag/service/TagCsvReader.java
back/src/test/java/com/cocktailpick/back/cocktail/domain/CocktailRepositoryTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/tag/Fixtures.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/CocktailTagsTest.java
back/src/test/java/com/cocktailpick/back/tag/domain/TagTest.java
back/src/test/java/com/cocktailpick/back/tag/service/TagServiceTest.java

Feat/129 id 관리를 BaseEntity에서 각 Entity로 넘겨주도록 수정한다.

---

back/src/docs/asciidocs/api-docs.adoc
back/src/main/java/com/cocktailpick/back/cocktail/domain/Cocktail.java
back/src/main/java/com/cocktailpick/back/tag/controller/TagController.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTagRepository.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/main/java/com/cocktailpick/back/tag/domain/Tag.java
back/src/main/java/com/cocktailpick/back/tag/dto/TagResponse.java
back/src/main/java/com/cocktailpick/back/tag/service/TagService.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/docs/CocktailDocumentation.java
back/src/test/java/com/cocktailpick/back/tag/controller/TagControllerTest.java
back/src/test/java/com/cocktailpick/back/tag/docs/TagDocumentation.java
back/src/test/java/com/cocktailpick/back/tag/service/TagServiceTest.java
front/src/api/index.js
front/src/component/admin/tag/TagItem.js

Feat/80 관리자 페이지에 태그 수정, 삭제 API를 구현한다.

---

back/src/docs/asciidocs/api-docs.adoc
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/tag/controller/TagController.java
back/src/main/java/com/cocktailpick/back/tag/domain/TagRepository.java
back/src/main/java/com/cocktailpick/back/tag/service/TagService.java
back/src/test/java/com/cocktailpick/back/tag/controller/TagControllerTest.java
back/src/test/java/com/cocktailpick/back/tag/docs/TagDocumentation.java
back/src/test/java/com/cocktailpick/back/tag/service/TagServiceTest.java

Feat/137 카테고리 별 태그를 조회하는 기능을 추가한다.

---

back/build.gradle
back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailRecommendService.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/favorite/domain/Favorites.java
back/src/main/java/com/cocktailpick/back/security/CurrentUser.java
back/src/main/java/com/cocktailpick/back/security/CustomUserDetailsService.java
back/src/main/java/com/cocktailpick/back/security/TokenAuthenticationFilter.java
back/src/main/java/com/cocktailpick/back/security/TokenProvider.java
back/src/main/java/com/cocktailpick/back/security/UserPrincipal.java
back/src/main/java/com/cocktailpick/back/tag/domain/CocktailTags.java
back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
back/src/main/java/com/cocktailpick/back/user/domain/EmptyUser.java
back/src/main/java/com/cocktailpick/back/user/domain/User.java
back/src/main/java/com/cocktailpick/back/user/dto/UserResponse.java
back/src/main/java/com/cocktailpick/back/user/service/UserService.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailRecommendServiceTest.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailServiceTest.java
back/src/test/java/com/cocktailpick/back/common/WithMockCustomUser.java
back/src/test/java/com/cocktailpick/back/common/WithMockCustomUserSecurityContextFactory.java
back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java

즐겨찾기 User 유무에 따른 분기 관련 백 로직 및 테스트 변경

---

back/src/main/java/com/cocktailpick/back/cocktail/domain/RecommendedCocktails.java
back/src/test/java/com/cocktailpick/back/cocktail/service/FilteringAndScoringRecommendServiceTest.java

Feat 121: 추천 알고리즘을 개선한다.

---

front/src/component/common/Header.js
front/src/component/common/MoblieNav.js
front/src/css/common/header.css

Hotfix/166 모바일 환경에서 사이드 메뉴 열릴 시 스크롤이 되는 버그를 수정한다.

---

front/src/component/common/Footer.js

아이콘 누르면 새 탭에 뜬다.

---

back/src/main/java/com/cocktailpick/back/security/TokenProvider.java
back/src/main/java/com/cocktailpick/back/security/UserPrincipal.java
back/src/main/java/com/cocktailpick/back/security/oauth2/CustomOAuth2UserService.java
back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
back/src/main/java/com/cocktailpick/back/user/domain/User.java
back/src/main/java/com/cocktailpick/back/user/dto/UserUpdateRequest.java
back/src/main/java/com/cocktailpick/back/user/service/AuthService.java
back/src/main/java/com/cocktailpick/back/user/service/UserService.java
back/src/test/java/com/cocktailpick/back/common/WithMockCustomUserSecurityContextFactory.java
back/src/test/java/com/cocktailpick/back/common/acceptance/AdminCreate.java
back/src/test/java/com/cocktailpick/back/user/acceptance/UserAcceptanceTest.java
back/src/test/java/com/cocktailpick/back/user/acceptance/step/UserAcceptanceStep.java
back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
back/src/test/java/com/cocktailpick/back/user/service/AuthServiceTest.java
back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
front/src/api/index.js
front/src/component/mypage/ProfileDetail.js
front/src/component/mypage/ProfileDetailInput.js
front/src/css/mypage/profile.css

resolve: #112 
이메일은 변경하지 않고, 이름만 변경하게 구현했습니다.
변경된 이름이 바로 적용되지 않아 수정 후 새로고침하게 하였습니다.

Feat/112 회원정보 수정 기능을 구현한다.

---

back/src/main/java/com/cocktailpick/back/security/oauth2/CustomOAuth2UserService.java
back/src/main/java/com/cocktailpick/back/user/domain/User.java
back/src/main/java/com/cocktailpick/back/user/service/AuthService.java
back/src/main/java/com/cocktailpick/back/user/service/UserService.java
back/src/test/java/com/cocktailpick/back/common/WithMockCustomUserSecurityContextFactory.java
back/src/test/java/com/cocktailpick/back/common/acceptance/AdminCreate.java
back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
back/src/test/java/com/cocktailpick/back/user/service/AuthServiceTest.java
back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java

시큐리티 코드에서 User 빈 객체 생성 후, 세터를 사용한 코드를 빌더로 변경했었습니다. #112 
그 부분에서 오류가 나서 테스트가 돌아가지 않는 현상이 발견하여 revert 후, pr 올립니다.

Hotfix: Lombok Builder Error

---

front/src/App.js
front/src/component/common/Footer.js
front/src/component/home/TodayCocktail.js

Feat/179 카카오톡 링크 요청이 한 번에 가지 않는 버그를 수정한다.

---

front/src/component/cocktailSearch/CocktailSearch.js
front/src/component/cocktailSearch/MoreButton.js
front/src/component/cocktailSearch/SearchContainer.js
front/src/component/cocktailSearch/TagFilterContainer.js
front/src/css/cocktailSearch/cocktailSearch.css

무한 스크롤링을 개선한다.

---

back/src/test/java/com/cocktailpick/back/user/acceptance/UserAcceptanceTest.java
back/src/test/java/com/cocktailpick/back/user/acceptance/step/UserAcceptanceStep.java

기존의 UserAccpetanceTest에 즐겨찾기 추가/조회/삭제 인수테스트를 추가했습니다 :)
resolve : #185

Feat/185 즐겨찾기 관련 인수테스트 추가한다.

---

back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
back/src/test/java/com/cocktailpick/back/user/acceptance/step/UserAcceptanceStep.java
back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
front/src/api/index.js

즐겨찾기 삭제 API의 url을 변경했습니다 :)
resolve: #202

Feat/202 즐겨찾기 삭제 API의 url을 변경한다.

---

back/src/docs/asciidocs/api-docs.adoc
back/src/main/java/com/cocktailpick/back/favorite/domain/Favorite.java
back/src/main/java/com/cocktailpick/back/favorite/domain/Favorites.java
back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
back/src/main/java/com/cocktailpick/back/user/domain/User.java
back/src/main/java/com/cocktailpick/back/user/dto/FavoriteCocktailIds.java
back/src/main/java/com/cocktailpick/back/user/dto/FavoriteCocktailIdsResponse.java
back/src/main/java/com/cocktailpick/back/user/service/UserService.java
back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
front/src/App.js
front/src/api/index.js
front/src/component/cocktailSearch/CocktailDetailSearch.js
front/src/component/cocktailSearch/CocktailFavorite.js
front/src/component/cocktailSearch/CocktailSearch.js
front/src/component/cocktailSearch/FavoriteIcon.js
front/src/component/cocktailSearch/NotFavoriteIcon.js
front/src/component/cocktailSearch/SearchContainer.js
front/src/component/cocktailSearch/SearchedCocktail.js
front/src/component/cocktailSearch/SearchedCocktails.js
front/src/component/cocktailSearch/TagFilterContainer.js
front/src/component/home/Home.js
front/src/component/home/TodayCocktail.js
front/src/component/recommend/Question.js
front/src/component/result/Result.js
front/src/component/result/ResultSlide.js
front/src/recoil/index.js
front/src/router/Routes.js

Feat/178 즐겨찾기한 칵테일들의 id 상태관리를 리코일로 변경한다.

---

back/src/main/java/com/cocktailpick/back/cocktail/controller/CocktailController.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailDetailResponse.java
back/src/main/java/com/cocktailpick/back/cocktail/dto/CocktailResponse.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailRecommendService.java
back/src/main/java/com/cocktailpick/back/cocktail/service/CocktailService.java
back/src/main/java/com/cocktailpick/back/user/dto/UserResponse.java
back/src/main/java/com/cocktailpick/back/user/service/UserService.java
back/src/test/java/com/cocktailpick/back/cocktail/controller/CocktailControllerTest.java
back/src/test/java/com/cocktailpick/back/cocktail/docs/CocktailDocumentation.java
back/src/test/java/com/cocktailpick/back/cocktail/service/CocktailRecommendServiceTest.java
back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java

Feat/201 CocktailResponse, CocktailDetailResponse Dto에서 favorite 필드 제거

---

front/src/api/index.js

resolve: #176 
API 요청 시 헤더를 변경하니 잘 되네요... 이거에 시간 오래 쓴게 너무 슬프네요

feat/176 로그인 버그를 수정한다.

---

front/src/component/alert/Alerts.js
front/src/component/cocktailSearch/CocktailDetailSearch.js
front/src/component/cocktailSearch/CocktailSearch.js
front/src/component/home/Recommendation.js
front/src/component/result/Result.js
front/src/css/recommend/abv.css
front/src/index.css

Feat/184 칵테일픽 UI를 개선한다.

---

front/src/component/alert/Alerts.js
front/src/component/cocktailSearch/CocktailSearch.js
front/src/component/cocktailSearch/MoreButton.js
front/src/component/cocktailSearch/SearchContainer.js
front/src/component/cocktailSearch/TagFilterContainer.js
front/src/constants/CocktailSearch.js
front/src/constants/index.js
front/src/css/cocktailSearch/cocktailSearch.css

Feat/221 칵테일 검색 결과 시 더 이상 결과가 없으면 더 보기 버튼을 제거한다.
